version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ../light_switcher_client
      dockerfile: Dockerfile
    ports:
      - "80:80"