version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"