version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/telegramdb
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
